### ISSUE TITLE
Get an error

### ISSUE THREAD

**Issue by whyisthesheep** [mam91/NeatResearch#20]
```
NLua.Exceptions.LuaScriptException: error loading module 'config' from file '.\config.lua':
	.\config.lua:7: invalid escape sequence near '"C:\U'

```

**Comment by pdrok** [comment]
you should replace `\` with `/` on the path
ex: instead of 
```
_M.BizhawkDir = "C:\Users\users\Documents\Ai\BizHawk-2.2\"
```
you should use: 
```
_M.BizhawkDir = "C:/Users/users/Documents/Ai/BizHawk-2.2/"
```

**Comment by whyisthesheep** [comment]
@pdrok Thank you but now I am getting this error
```
NLua.Exceptions.LuaScriptException: A .NET exception occured in user-code
System.Exception: Essential zip section not found: BizVersion
   at BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback, Boolean isZstdCompressed)
   at BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`1 callback)
   at BizHawk.Client.Common.SavestateFile.Load(String path, IDialogParent dialogParent)
   at BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean suppressOSD)
   at BizHawk.Client.Common.SaveStateLuaLibrary.Load(String path, Boolean suppressOSD)
```

**Comment by Omniscye** [comment]
Don’t bother.  The Loading of saved data still does not work. Even with the code that was mentioned in another post. It will not load the state.pool file

**Comment by whyisthesheep** [comment]
@AxelMGrey ah ok so the project currently doesn't work?

**Comment by pdrok** [comment]
The project is working, but the issue could be related to the folder where you placed the file. You need to carefully read the instruction part in the README file.
I got it running on Windows 11 with BizHawk-2.2.

![image](https://user-images.githubusercontent.com/1653791/236025681-e389d246-9309-407e-a829-63a511d58afd.png)

**Comment by Omniscye** [comment]
> The project is working, but the issue could be related to the folder where you placed the file. You need to carefully read the instruction part in the README file. I got it running on Windows 11 with BizHawk-2.2.
> 
> ![image](https://user-images.githubusercontent.com/1653791/236025681-e389d246-9309-407e-a829-63a511d58afd.png)

It works, but it will NOT load! You can not los the file back. The issue isn’t it working, it’s loading.  This new file system does not work. None of them do.

**Comment by Omniscye** [comment]
> @AxelMGrey ah ok so the project currently doesn't work?

It works, just the loading doesn’t work. The read me is lying. Try it yourself.  You can save but you won’t be able to load. Don’t listen to anyone saying it does. All Forks with this new fuel system does not LOAD

**Comment by pdrok** [comment]
![image](https://user-images.githubusercontent.com/1653791/236048702-f21f5595-fc08-47ce-ac71-f25c78f0176e.png)
I was able to load the save state, also replay the top score for each save.  It works on my machine. :)

**Comment by Omniscye** [comment]
> ![image](https://user-images.githubusercontent.com/1653791/236048702-f21f5595-fc08-47ce-ac71-f25c78f0176e.png) I was able to load the save state, also replay the top score for each save. It works on my machine. :)


Thats awesome!  You had to of edited the lua tho.  All I get is Nill and neuron error while loading.  As do 99% of people on here on all forks with the new saving/loading.  Can you share it if you could?

**Comment by pdrok** [comment]
I put the folder `neat-mario` from this repository inside the folder: `BizHawk-2.2\Lua\SNES\`

![image](https://user-images.githubusercontent.com/1653791/236054710-6f3beed9-f467-4ea9-b92f-8c9023686593.png)

Then I changed the following on the file `neat-mario\config.lua`: 
![image](https://user-images.githubusercontent.com/1653791/236054355-2c272462-9624-434e-9452-dc7be843ad3c.png)

you need to put your own directory path there where you put the BizHawk unziped, ex:
```
C:/Users/YOUR_USER/Downloads/BizHawk-2.2/
```

Then I open the script:
![image](https://user-images.githubusercontent.com/1653791/236054876-b65a66ae-3ccd-430f-8fae-41682d943eec.png)

Then I load the last state pool and press start

![image](https://user-images.githubusercontent.com/1653791/236056675-7971f7d1-499b-4f3a-96ef-d0b4aff4219e.png)

![image](https://user-images.githubusercontent.com/1653791/236056721-9c988bd6-d930-43d2-a650-654b203b9f40.png)

**Comment by Omniscye** [comment]
> I put the folder `neat-mario` from this repository inside the folder: `BizHawk-2.2\Lua\SNES\`
> 
> ![image](https://user-images.githubusercontent.com/1653791/236054710-6f3beed9-f467-4ea9-b92f-8c9023686593.png)
> 
> Then I changed the following on the file `neat-mario\config.lua`: ![image](https://user-images.githubusercontent.com/1653791/236054355-2c272462-9624-434e-9452-dc7be843ad3c.png)
> 
> you need to put your own directory path there where you put the BizHawk unziped, ex:
> 
> ```
> C:/Users/YOUR_USER/Downloads/BizHawk-2.2/
> ```
> 
> Then I open the script: ![image](https://user-images.githubusercontent.com/1653791/236054876-b65a66ae-3ccd-430f-8fae-41682d943eec.png)
> 
> Then I load the last state pool and press start
> 
> ![image](https://user-images.githubusercontent.com/1653791/236056675-7971f7d1-499b-4f3a-96ef-d0b4aff4219e.png)
> 
> ![image](https://user-images.githubusercontent.com/1653791/236056721-9c988bd6-d930-43d2-a650-654b203b9f40.png)

I’ll give it a worl thank you.   So you load the Latest state pool.  Not the Main state.pool that stays the same.   I think I was trying in 2.2.2 😂 maybe that’s why it didn’t work. Lol.

**Comment by Omniscye** [comment]
> I put the folder `neat-mario` from this repository inside the folder: `BizHawk-2.2\Lua\SNES\`
> 
> ![image](https://user-images.githubusercontent.com/1653791/236054710-6f3beed9-f467-4ea9-b92f-8c9023686593.png)
> 
> Then I changed the following on the file `neat-mario\config.lua`: ![image](https://user-images.githubusercontent.com/1653791/236054355-2c272462-9624-434e-9452-dc7be843ad3c.png)
> 
> you need to put your own directory path there where you put the BizHawk unziped, ex:
> 
> ```
> C:/Users/YOUR_USER/Downloads/BizHawk-2.2/
> ```
> 
> Then I open the script: ![image](https://user-images.githubusercontent.com/1653791/236054876-b65a66ae-3ccd-430f-8fae-41682d943eec.png)
> 
> Then I load the last state pool and press start
> 
> ![image](https://user-images.githubusercontent.com/1653791/236056675-7971f7d1-499b-4f3a-96ef-d0b4aff4219e.png)
> 
> ![image](https://user-images.githubusercontent.com/1653791/236056721-9c988bd6-d930-43d2-a650-654b203b9f40.png)

Wait, you only changed the 2nd directory?  Not the top one?  Why not both.

**Comment by JetpackFandango** [comment]
I followed all of these steps exactly and I still got this error `NLua.Exceptions.LuaScriptException: A .NET exception occured in user-code
System.Exception: Essential zip section not found: BizVersion
   at BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback, Boolean isZstdCompressed)
   at BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`1 callback)
`

**Comment by CoriDrysdale** [comment]
> I followed all of these steps exactly and I still got this error `NLua.Exceptions.LuaScriptException: A .NET exception occured in user-code System.Exception: Essential zip section not found: BizVersion at BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback, Boolean isZstdCompressed) at BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`1 callback) `

I was able to resolve this error by replacing the DP1.state file in neat-mario/pool with my own DP1.state file.

Would be helpful if adding the DP1.state file to neat-mario/pool was a part of the readme, I think. 

This just gets the script to run though, it looks like loading might still be broken. I couldn't get the FitnessChangesOnly/ script to run either.

**Comment by kylechallis** [comment]
The project also works for me.

Make sure you're using BizHawk 2.2.2 (not just 2.2), and make sure you're using BizHawk prerequisites 2.1
